[package]
name = "dot_product"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bytemuck = "1.25.0"
env_logger = "0.11.9"
flume = "0.12.0"
pollster = "0.4.0"
rand = "0.10.0"
wgpu = "28.0.0"
