[package]
name = "vector_add"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
bytemuck = { version = "1.25.0", features = ["derive"] }
env_logger = "0.11.9"
flume = "0.12.0"
pollster = "0.4.0"
rand = "0.10.0"
wgpu = "28.0.0"
